name: pythonista_skewedf_dev
channels:
  - conda-forge
  - r
dependencies:
  - r-base=4.1
  - r-irkernel
  - r-tidyverse
  - r-rcpp
  - r-zipfR
  - r-optimr
  - r-matrixstats
  - r-stringr
  - pip
  - pip:
    - .
    - scipy
    - numpy
    - statsmodels
    - pandas
    - matplotlib
    - seaborn
    - openpyxl
    - rich
    - nbgitpuller
    - jupytext